#!/usr/bin/env bash
# deploy.sh (VM1 infra) — bring up MySQL + MinIO, then write vm2-shared.env
# with what VM2 needs to connect (host, DB user/password, MinIO keys).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

if ! command -v docker &>/dev/null; then
    echo "ERROR: Docker not found. Install it first: https://docs.docker.com/engine/install/"
    exit 1
fi

gen_alnum() {
    # head closes the pipe as soon as it has $1 bytes, so tr gets SIGPIPE
    # (exit 141) — harmless, but pipefail+set -e would otherwise abort
    # the script on it. Scoped to a subshell so pipefail stays on globally.
    local len="$1"
    ( set +o pipefail; LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$len" )
}

gen_password() {
    gen_alnum 10
}

# Escapes \, | and & so a value is safe as a sed replacement below.
sed_escape() {
    printf '%s' "$1" | sed -e 's/[\\|&]/\\&/g'
}

set_env() {
    sed -i "s|^$1=.*|$1=$(sed_escape "$2")|" .env
}

# Private IP MySQL (3306) and MinIO (9000) are published on — VM2 connects to it.
# Detected from the default route's source address on every run; on a multi-NIC
# VM override it: VM1_PRIVATE_IP=10.0.0.5 ./deploy.sh
if [[ -z "${VM1_PRIVATE_IP:-}" ]]; then
    VM1_PRIVATE_IP=$(ip -4 route get 1.1.1.1 2>/dev/null | sed -n 's/.* src \([0-9.]*\).*/\1/p')
fi
if [[ ! "${VM1_PRIVATE_IP:-}" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]]; then
    echo "ERROR: could not detect this VM's private IP."
    echo "  Pass it explicitly: VM1_PRIVATE_IP=<ip from 'ip -4 addr'> ./deploy.sh"
    exit 1
fi
# Docker can only publish on an address this VM actually has.
if command -v ip &>/dev/null && ! ip -o -4 addr show | grep -qw "inet ${VM1_PRIVATE_IP}"; then
    echo "ERROR: ${VM1_PRIVATE_IP} is not assigned to any interface on this VM."
    echo "  Use the private IP shown by: ip -4 addr"
    exit 1
fi
export VM1_PRIVATE_IP
echo "Using VM1 private IP: ${VM1_PRIVATE_IP}"

if [[ ! -f .env ]]; then
    if [[ ! -f .env.example ]]; then
        echo "ERROR: .env.example not found."
        exit 1
    fi

    echo "No .env found — running first-time setup."

    cp .env.example .env

    echo "Generating passwords..."
    set_env MYSQL_ROOT_PASSWORD "$(gen_password)"
    set_env MYSQL_PASSWORD "$(gen_password)"
    set_env MINIO_ROOT_PASSWORD "$(gen_password)"

    echo "✓ .env created — 3 passwords generated."
fi

echo ""
echo "Starting MySQL and MinIO..."
docker compose up -d

bash minio-setup.sh

echo "Waiting for MySQL to become healthy (first boot runs init-db, can take a minute)..."
tries=0
until [[ "$(docker inspect -f '{{.State.Health.Status}}' cyberwise-mysql 2>/dev/null)" == "healthy" ]]; do
    tries=$((tries + 1))
    if (( tries > 90 )); then
        echo "ERROR: MySQL did not become healthy in time. Check: docker compose logs mysql"
        exit 1
    fi
    sleep 2
done
echo "✓ MySQL healthy"

# Re-read: minio-setup.sh may have just written the MinIO keys.
set -a
# shellcheck disable=SC1091
source .env
set +a

(
    umask 077
    cat > vm2-shared.env <<EOF
# Generated by vm1-infra/deploy.sh — copy to vm2-app/vm2-shared.env on VM2.
VM1_HOST=${VM1_PRIVATE_IP}
MYSQL_USER=${MYSQL_USER}
MYSQL_PASSWORD=${MYSQL_PASSWORD}
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
EOF
)

echo ""
echo "=== VM1 infra ready ==="
echo "  MySQL:  ${VM1_PRIVATE_IP}:3306"
echo "  MinIO:  ${VM1_PRIVATE_IP}:9000   (console: 127.0.0.1:9001, SSH-tunnel only)"
echo ""
echo "Next: copy $(pwd)/vm2-shared.env to vm2-app/ on VM2, e.g."
echo "  scp vm2-shared.env <user>@<VM2>:<path>/installer-2vm/vm2-app/"
echo "then run vm2-app/deploy.sh on VM2."
echo ""
echo "Firewall: allow ${VM1_PRIVATE_IP}:3306 and :9000 from VM2's IP only."
